project:
  type: website
  output-dir: docs

website:
  title: "Rory Spurr"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: minty
    css: styles.css
    toc: true



